# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_ROCKCHIP_MPP_SERVICE) += mpp/
obj-$(CONFIG_ROCKCHIP_RGA) += rga/
obj-$(CONFIG_VIDEO_ROCKCHIP_FEC) += fec/
obj-$(CONFIG_VIDEO_ROCKCHIP_AVSP) += avsp/

